$(document).ready(function(){
  $("#development-image").click(function(){
    $("#development-image").slideToggle(3000);
    $("#development").slideToggle(3000);
  });
  $("#development").click(function(){
    $("#development").slideToggle(3000);
    $("#development-image").slideToggle(3000);
  });
});

$(document).ready(function(){
  $("#design-image").click(function(){
    $("#design-image").slideToggle(3000);
    $("#design").slideToggle(3000);
  });
  $("#design").click(function(){
    $("#design").slideToggle(3000);
    $("#design-image").slideToggle(3000);
  });
});

$(document).ready(function(){
  $("#product-image").click(function(){
    $("#product-image").slideToggle(3000);
    $("#product").slideToggle(3000);
  });
  $("#product").click(function(){
    $("#product").slideToggle(3000);
    $("#product-image").slideToggle(3000);
  });
});

$(document).ready(function(){
  $("#fish-image").click(function(){
    $("#fish-image").slideToggle(3000);
    $("#fish").slideToggle(3000);
  });
  $("#fish").click(function(){
    $("#fish").slideToggle(3000);
    $("#fish-image").slideToggle(3000);
  });
});

$(document).ready(function(){
  $("#spaghetti-image").click(function(){
    $("#spaghetti-image").slideToggle(3000);
    $("#spaghetti").slideToggle(3000);
  });
  $("#spaghetti").click(function(){
    $("#spaghetti").slideToggle(3000);
    $("#spaghetti-image").slideToggle(3000);
  });
});

$(document).ready(function(){
  $("#mukimo-image").click(function(){
    $("#mukimo-image").slideToggle(3000);
    $("#mukimo").slideToggle(3000);
  });
  $("#mukimo").click(function(){
    $("#mukimo").slideToggle(3000);
    $("#mukimo-image").slideToggle(3000);
  });
});

$(document).ready(function(){
  $("#fish-image").click(function(){
    $("#fish-image").slideToggle(3000);
    $("#fish").slideToggle(3000);
  });
  $("#fish").click(function(){
    $("#fish").slideToggle(3000);
    $("#fish-image").slideToggle(3000);
  });
});

$(document).ready(function(){
  $("#spaghetti-image").click(function(){
    $("#spaghetti-image").slideToggle(3000);
    $("#spaghetti").slideToggle(3000);
  });
  $("#spaghetti").click(function(){
    $("#spaghetti").slideToggle(3000);
    $("#spaghetti-image").slideToggle(3000);
  });
});

$(document).ready(function(){
  $("#mukimo-image").click(function(){
    $("#mukimo-image").slideToggle(3000);
    $("#mukimo").slideToggle(3000);
  });
  $("#mukimo").click(function(){
    $("#mukimo").slideToggle(3000);
    $("#mukimo-image").slideToggle(3000);
  });
});
